### ISSUE TITLE
IsProbablePrime returning invalid result

### ISSUE THREAD

**Issue by mmcc1** [bazzilic/BigIntegerExt#6]
I tested IsProbablePrime with the First Oakley Default Group:

```
private byte[] m_OAKLEY768 = new byte[] {
                                                    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC9, 0x0F, 0xDA, 0xA2,
                                                    0x21, 0x68, 0xC2, 0x34, 0xC4, 0xC6, 0x62, 0x8B, 0x80, 0xDC, 0x1C, 0xD1,
                                                    0x29, 0x02, 0x4E, 0x08, 0x8A, 0x67, 0xCC, 0x74, 0x02, 0x0B, 0xBE, 0xA6,
                                                    0x3B, 0x13, 0x9B, 0x22, 0x51, 0x4A, 0x08, 0x79, 0x8E, 0x34, 0x04, 0xDD,
                                                    0xEF, 0x95, 0x19, 0xB3, 0xCD, 0x3A, 0x43, 0x1B, 0x30, 0x2B, 0x0A, 0x6D,
                                                    0xF2, 0x5F, 0x14, 0x37, 0x4F, 0xE1, 0x35, 0x6D, 0x6D, 0x51, 0xC2, 0x45,
                                                    0xE4, 0x85, 0xB5, 0x76, 0x62, 0x5E, 0x7E, 0xC6, 0xF4, 0x4C, 0x42, 0xE9,
                                                    0xA6, 0x3A, 0x36, 0x20, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00
                                                };
```
https://tools.ietf.org/html/rfc2409

Your method returns false.  It should be true.

**Comment by bazzilic** [comment]
Are you sure that the byte order and encoding in the RFC is the same as in .NET BigInteger implementation?

**Comment by mmcc1** [comment]
I have a functional copy using a Mono implementation of BigInteger.  I have double checked the values in decimal and they are the same, so its not a byte order issue.  I also tried replacing your IsPrime with other implementations and I get the same issue.  I think everyone is copying the same bug.

**Comment by mmcc1** [comment]
You can compare your code with this implementation which uses mono.  It is wrapped up in a Diffie Hellman app, but its light weight.  Look for isProbablePrime:

http://www.mentalis.org/soft/class.qpx?id=15

**Comment by Yifan-Ethan** [comment]
I believe the issue here is due to the fact that the First Oakley Default group is in fact not a prime number, hence isProbablePrime is returning false. 

I have tested its decimal value
`1552518092300708935075407227560812055952790782792057789504633272224559145203236185365842723154162683436086814015206822700649647473957997443235909597749047221761620416914691629282469033410940619377877075948497055733157454752807649279` against many online prime number calculators, as well as a personal implementation of a prime number investigator, all of which returns false.
I have also tested a prime number of similar length (241 digits) and a large prime number (500 digits) to ensure the integrity of isProbablePrime, to which it returns true, so isProbablePrime definitely has no issues checking large numbers.

@mmcc1 Could you clarify why should First Oakley Default Group return true if it is not prime? From my understanding this standard has been obsolete since 2005.

**Comment by Yifan-Ethan** [comment]
`1552518092300708935075407227560812055952790782792057789504633272224559145203236185365842723154162683436086814015206822700649647473957997443235909597749047221761620416914691629282469033410940619377877075948497055733157454752807649279` is divisible by 7.

**Comment by Yifan-Ethan** [comment]
@mmcc1  This is because your byte array gives us the wrong base 10 value when passed into BigInteger. Try

```
String hexString = "0FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6F44C42E9A63A3620FFFFFFFFFFFFFFFF";
BigInteger BigInt = BigInteger.Parse(hexString, NumberStyles.AllowHexSpecifier);
```
which will give you

`1552518092300708935130918131258481755631334049434514313202351194902966239949102107258669453876591642442910007680288864229150803718918046342632727613031282983744380820890196288509170691316593175367469551763119843371637221007210577919`

I don't think there is anything wrong with isProbablePrime

**Comment by bazzilic** [comment]
Closing this. If you have any additional information on this issue, please reopen.
